/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: traceboy.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "traceboy.pb-c.h"
void   trace_packet__init
                     (TracePacket         *message)
{
  static const TracePacket init_value = TRACE_PACKET__INIT;
  *message = init_value;
}
size_t trace_packet__get_packed_size
                     (const TracePacket *message)
{
  assert(message->base.descriptor == &trace_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trace_packet__pack
                     (const TracePacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trace_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trace_packet__pack_to_buffer
                     (const TracePacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trace_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TracePacket *
       trace_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TracePacket *)
     protobuf_c_message_unpack (&trace_packet__descriptor,
                                allocator, len, data);
}
void   trace_packet__free_unpacked
                     (TracePacket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trace_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   empty__init
                     (Empty         *message)
{
  static const Empty init_value = EMPTY__INIT;
  *message = init_value;
}
size_t empty__get_packed_size
                     (const Empty *message)
{
  assert(message->base.descriptor == &empty__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t empty__pack
                     (const Empty *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &empty__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t empty__pack_to_buffer
                     (const Empty *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &empty__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Empty *
       empty__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Empty *)
     protobuf_c_message_unpack (&empty__descriptor,
                                allocator, len, data);
}
void   empty__free_unpacked
                     (Empty *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &empty__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor trace_packet__field_descriptors[4] =
{
  {
    "game_rom_crc32",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TracePacket, game_rom_crc32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TracePacket, start_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_inputs",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TracePacket, user_inputs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_state_crc32",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TracePacket, end_state_crc32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trace_packet__field_indices_by_name[] = {
  3,   /* field[3] = end_state_crc32 */
  0,   /* field[0] = game_rom_crc32 */
  1,   /* field[1] = start_state */
  2,   /* field[2] = user_inputs */
};
static const ProtobufCIntRange trace_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor trace_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TracePacket",
  "TracePacket",
  "TracePacket",
  "",
  sizeof(TracePacket),
  4,
  trace_packet__field_descriptors,
  trace_packet__field_indices_by_name,
  1,  trace_packet__number_ranges,
  (ProtobufCMessageInit) trace_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define empty__field_descriptors NULL
#define empty__field_indices_by_name NULL
#define empty__number_ranges NULL
const ProtobufCMessageDescriptor empty__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Empty",
  "Empty",
  "Empty",
  "",
  sizeof(Empty),
  0,
  empty__field_descriptors,
  empty__field_indices_by_name,
  0,  empty__number_ranges,
  (ProtobufCMessageInit) empty__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor trace_db__method_descriptors[1] =
{
  { "Submit", &trace_packet__descriptor, &empty__descriptor },
};
const unsigned trace_db__method_indices_by_name[] = {
  0         /* Submit */
};
const ProtobufCServiceDescriptor trace_db__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "TraceDB",
  "TraceDB",
  "TraceDB",
  "",
  1,
  trace_db__method_descriptors,
  trace_db__method_indices_by_name
};
void trace_db__submit(ProtobufCService *service,
                      const TracePacket *input,
                      Empty_Closure closure,
                      void *closure_data)
{
  assert(service->descriptor == &trace_db__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void trace_db__init (TraceDB_Service *service,
                     TraceDB_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &trace_db__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
